### ISSUE TITLE
media queries

### ISSUE THREAD

**Issue by krisbulman** [at-import/jacket#1]
What's the recommended way of pulling styles out of media queries with jacket? (in the case of ie8) Or is breakpoint no-queries still recommended for that task?

**Comment by robwierzbowski** [comment]
For now you should probably use no-queries. But, I have a fork of Breakpoint 2.x with some extra features that I'm going to integrate with Jacket sometime this week. When that's done an author will be able to use a single interface for all of their contextual rules. 

Something like:

``` scss
.rule {
  @include breakpoint( (20em) (min-color 8) (jacket old-ie) ) {
    ...
  }
}
```

And then in your style.oldie.scss:

``` scss
$jacket: old-ie;
@import 'style';
```

**Comment by krisbulman** [comment]
very cool, i'll be looking forward to the commits.

**Comment by robwierzbowski** [comment]
I look forward to making them :D.

**Comment by robwierzbowski** [comment]
While I was playing around with multiple jacket contexts per stylesheet I wrote a small media query fallback mixin. You'll be able to find it in the tests as an example from now on: https://github.com/Team-Sass/jacket/blob/master/test/scss/style.scss#L128

I think it's fine for production, if you're looking for something simple.

**Comment by krisbulman** [comment]
Nice, I'll try this out, thanks.
