### ISSUE TITLE
Output conditional style only into the conditional stylesheet

### ISSUE THREAD

**Issue by polikin** [at-import/jacket#4]
It it possible to output only the conditional style in my conditional stylesheet? Because, I don't want to add weight to my conditional sheet. The only thing I want is the fix I did for IE.

Ex: 

```
.exemple {
    width: 100px;
    height: 300px;

    @include jacket(ie8) {
        width: 200px;
    }
}
```

output css:

screen.css

```
.exemple {
    width: 100px;
    height: 300px;
}
```

ie8.css

```
.ie8 .exemple {
    width: 200px;
}
```

rather than

screen.css

```
.exemple {
    width: 100px;
    height: 300px;
}
```

ie8.css

```
.exemple {
    width: 100px;
    height: 300px;
}

.ie8 .exemple {
    width: 200px;
}
```

**Comment by robwierzbowski** [comment]
Unfortunately Sass doesn't work that way — I think it's mostly discussed in this issue: https://github.com/nex3/sass/issues/241

Currently conditional style mixins like Jacket and Breakpoint create complete stylesheets which you conditionally supply to your browsers. Give IE8 only the IE8 stylesheet (with conditional comments), and the same with the standards browsers.

**Comment by polikin** [comment]
Thanks!

**Comment by robwierzbowski** [comment]
No problem :smile:
