### ISSUE TITLE
function jacketOrElse

### ISSUE THREAD

**Issue by Hannes-III** [at-import/jacket#6]
for my project I have implemented a Function like that:

``` scss
@function jacketOrElse($value, $else, $contexts...) {}
```

It will return `$value` if the `$contexts` match or `$else` if not.
If you think his would be an interesting addition to Jacket, drop me a note. I will Fork Jacket and place a pull request.

I had to implement his function because I did not find a way to get a Value if none of the `$contexts` matched.

Regards, Hannes

**Comment by Hannes-III** [comment]
Yesterday I found a case where it showed that this functionality is even necessary because my workaround did not work:
I used this syntax to get this or that value in a function:

``` scss
  @return jacket($rem-list, all) jacket($px-list, ielt9);
```

This worked fine up to yesterday, where I found out that this returns a List with a null value, which Is not what I wanted.

**Comment by robwierzbowski** [comment]
That's a decent idea, PR welcome. Would you mind calling the function `jacket-else`, to stay brief and keep with CSS style function names?

**Comment by Hannes-III** [comment]
Thank you for looking @ the pull request. More comments there. I'll close this issue now.
